export const tiposPokemon = {
    normal: { cor: '#a8a77a', icon: "fa-regular fa-circle-dot"},
    fire: {cor: '#EE8130', icon: "fa-solid fa-fire"},
    water: {cor: '#6390F0', icon: "fa-solid fa-water"},
    electric: {cor: '#F7D02C', icon: "fa-solid fa-bolt-lightning"},
    grass: {cor: '#7AC74C', icon: "fa-solid fa-seedling"},
    ice: {cor: '#96D9D6', icon: "fa-solid fa-snowflake"},
    fighting: {cor: '#C22E28', icon: "fa-solid fa-hand-fist"},
    poison: {cor: '#A33EA1', icon: "fa-solid fa-skull-crossbones"},
    ground: {cor: '#E2BF65', icon: "fa-solid fa-mountain"},
    flying: {cor: '#A98FF3', icon: "fa-solid fa-wind"},
    psychic: {cor: '#F95587', icon: "fa-solid fa-brain"},
    bug: {cor: '#A6B91A', icon: "fa-solid fa-bug"},
    rock: {cor: '#B6A136', icon: "fa-solid fa-hill-rockslide"},
    ghost: {cor: '#735797', icon: "fa-solid fa-ghost"},
    dragon: {cor: '#6F35FC', icon: "fa-solid fa-dragon"},
    dark: {cor: '#705746', icon: "fa-brands fa-sith"},
    steel: {cor: '#B7B7CE', icon: "fa-solid fa-magnet"},
    fairy: {cor: '#D685AD', icon: "fa-solid fa-hand-sparkles"}
}